using log4net;
using Microsoft.AspNetCore.Builder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Helper
{
    //public class ExceptionMiddlewareExtension
    //{
    //    public static void ConfigureExceptionHandler(this IApplicationBuilder app, ILog logger)
    //    {
    //        app.UseExceptionHandler(appError =>
    //        {
    //            appError.Run(async context =>
    //            {
    //                context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
    //                context.Response.ContentType = "application/json";

    //                var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
    //                if (contextFeature != null)
    //                {
    //                    logger.Error($"Something went wrong: {contextFeature.Error}");

    //                    await context.Response.WriteAsync(new ErrorDetails()
    //                    {
    //                        StatusCode = context.Response.StatusCode,
    //                        Message = "Internal Server Error. Error generated by NLog!"
    //                    }.ToString());
    //                }
    //            });
    //        });
    //    }
    //}
}
